robot:
  server: "http://192.168.31.8:9527"
  token: "yqchilde"

plugins:
  emoticon:
    enable: true
    dir: "./imgs/emoticon"
    bedUser: ""
    bedPass: ""

  plmm:
    enable: true
    url: "https://www.mxnzp.com/api/image/girl/list/random"
    appId: ""
    appSecret: ""

  weather:
    enable: true
    key: ""

  cronjob:
    enable: true
    myb:
      cron: "0 30 9 * * *"
      groups: [ "卤蛋群","Test" ]
